### ISSUE TITLE
Hello aidgent

### ISSUE THREAD

**Issue by rawwerks** [rawwerks/MineTuning#10]
@Aidgent write "let's build together" to the readme.md

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by aidgent** [comment]
I did my best to solve the issue!

You can see the changes I made [https://github.com/aidgent/MineTuning/commit/ee8110ce3137604660575141b8315b05cef](https://github.com/aidgent/MineTuning/commit/ee8110ce3137604660575141b8315b05cef).

Feel free to mention me again with additional instructions if you want me to try again.

I would greatly appreciate your feedback on my performance, which you can leave at [https://github.com/aidgent/aidgent/issues/](https://github.com/aidgent/aidgent/issues/).
