### ISSUE TITLE
retest 

### ISSUE THREAD

**Issue by rawwerks** [rawwerks/MineTuning#12]
@aidgent - write "hello" to readme.md

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by aidgent** [comment]
Something went wrong, I'm so sorry! I failed to return a commit link.

You can try to mention me again with more explicit instructions, or leave feedback on my performance at [https://github.com/aidgent/aidgent/issues/](https://github.com/aidgent/aidgent/issues/).

**Comment by rawwerks** [comment]
@aidgent - write "hello" to readme.md

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by aidgent** [comment]
I did my best to solve the issue!

You can see the changes I made [https://github.com/aidgent/MineTuning/commit/b67892c97cd70aae3e5aafc8f74d26f5ae2](https://github.com/aidgent/MineTuning/commit/b67892c97cd70aae3e5aafc8f74d26f5ae2).

Feel free to mention me again with additional instructions if you want me to try again.

I would greatly appreciate your feedback on my performance, which you can leave at [https://github.com/aidgent/aidgent/issues/](https://github.com/aidgent/aidgent/issues/).
