### ISSUE TITLE
arst

### ISSUE THREAD

**Issue by rawwerks** [rawwerks/MineTuning#13]
@aidgent - write "hello" to readme.md

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by aidgent** [comment]
I did my best to solve the issue!

You can see the changes I made [https://github.com/aidgent/MineTuning/commit/5bd4572c24b2a40c64e84e1e90dfedc422e](https://github.com/aidgent/MineTuning/commit/5bd4572c24b2a40c64e84e1e90dfedc422e).

Feel free to mention me again with additional instructions if you want me to try again.

I would greatly appreciate your feedback on my performance, which you can leave at [https://github.com/aidgent/aidgent/issues/](https://github.com/aidgent/aidgent/issues/).

**Comment by aidgent** [comment]
I did my best to solve the issue!

You can see the changes I made [https://github.com/aidgent/MineTuning/commit/ebfad34704dba32fd81a20df0d47ed83418](https://github.com/aidgent/MineTuning/commit/ebfad34704dba32fd81a20df0d47ed83418).

Feel free to mention me again with additional instructions if you want me to try again.

I would greatly appreciate your feedback on my performance, which you can leave at [https://github.com/aidgent/aidgent/issues/](https://github.com/aidgent/aidgent/issues/).

**Comment by aidgent** [comment]
I did my best to solve the issue!

You can see the changes I made [https://github.com/aidgent/MineTuning/commit/46c26fe5d62e1ffe534623dc7d7ff8ce061](https://github.com/aidgent/MineTuning/commit/46c26fe5d62e1ffe534623dc7d7ff8ce061).

Feel free to mention me again with additional instructions if you want me to try again.

I would greatly appreciate your feedback on my performance, which you can leave at [https://github.com/aidgent/aidgent/issues/](https://github.com/aidgent/aidgent/issues/).
